### ISSUE TITLE
Implement remaining TestCafes

### ISSUE THREAD

**Issue by giorgio-tran** [ics414t3/ics-osm#162]

**Comment by graquepo** [comment]
- [x] Add Faculty (Malia)
- [x] Edit Faculty (Malia)
- [x] Add Room (Susan)
- [x] Edit Room (Susan)
- [x] Add Equipment (Susan)
- [x] Edit Equipment (Susan)
- [x] Add Jack (Susan)
- [x] Edit Jack (Susan)
- [x] Add Club (Gwen)
- [x] Edit Club (Gwen)
- [x] Add Officer (Gwen)
- [x] Add Student (Giorgio)
- [x] Edit Student (Giorgio)
- [x] Add Staff (Malia)
- [x] Edit Staff (Malia)
