### ISSUE TITLE
Review: Faculty.jsx and Landing.jsx

### ISSUE THREAD

**Issue by giorgio-tran** [ics414t3/ics-osm#56]
## Review Branch

- [review-56](https://github.com/ics414t3/ics-osm/tree/review-56)

## Files to review

- [Faculty.jsx](https://github.com/ics414t3/ics-osm/blob/6a6dab05252b30de93fe832f0b19e7952531438a/app/imports/ui/pages/Faculty.jsx)
- [Landing.jsx](https://github.com/ics414t3/ics-osm/blob/main/app/imports/ui/pages/Landing.jsx)

## Checklists

- [Architecture](https://github.com/cammoore/campus-cravings/tree/master/checklists/architecture-checklist.md)
- [Design](https://github.com/cammoore/campus-cravings/tree/master/checklists/design-checklist.md)
- [JS](https://github.com/cammoore/campus-cravings/tree/master/checklists/js-checklist.md)
- [React](https://github.com/cammoore/campus-cravings/tree/master/checklists/react-checklist.md)

## Due Date

1/30/2023

**Comment by susankpma** [comment]
Faculty.jsx
Add more comments
ESlint


Landing.jsx
Lines 8-10: dead code remove <Col>
Lines 13-14: use Col or div to control the layout

**Comment by giorgio-tran** [comment]
### Faculty.jsx

L45-88: REACT-01: Modal could be refactored into its own component

L90-101: REACT-01: Modal could be refactored into its own component

### Landing.jsx

L8-10: Not sure if this is needed since it’s empty

L13-14: Can be condensed into a single div

**Comment by JeromeWasserman** [comment]
Faculty.jsx
Design-05,07:*Need more comments

Landing.jsx
Also the same as Faculty.jsx

**Comment by malialiu** [comment]
Landing.jsx
consider how it looks in different view (desktop, phone, etc.)

**Comment by graquepo** [comment]
Faculty.jsx
ESLint Spacing etc

Landing.jsx
Design 1 Line 13-14: Could use </br> to create a new line instead of creating a new <p></p> div
Design 3 Line 8-10: There is a Col and h1 div but there’s nothing inside

**Comment by darquines** [comment]
Faculty.jsx
ESLint spacing and add additional comments
