### ISSUE TITLE
Review: ListRoom.jsx and FacultyRolesCollection.js

### ISSUE THREAD

**Issue by giorgio-tran** [ics414t3/ics-osm#68]
## Review Branch

- [review-68](https://github.com/ics414t3/ics-osm/tree/review-68)

## Files to review

- [ListRoom.jsx](https://github.com/ics414t3/ics-osm/blob/review-68/app/imports/ui/pages/ListRoom.jsx)
- [FacultyRolesCollection.js](https://github.com/ics414t3/ics-osm/blob/review-68/app/imports/api/faculty/FacultyRolesCollection.js)

## Checklists

- [Architecture](https://github.com/cammoore/campus-cravings/tree/master/checklists/architecture-checklist.md)
- [Design](https://github.com/cammoore/campus-cravings/tree/master/checklists/design-checklist.md)
- [JS](https://github.com/cammoore/campus-cravings/tree/master/checklists/js-checklist.md)
- [React](https://github.com/cammoore/campus-cravings/tree/master/checklists/react-checklist.md)

## Due Date

2/8/2023

**Comment by susankpma** [comment]
ListRoom
Design-05 update comments references room item which is not used
Design-07 image alt tag should be meaningful
Design-08 image style in css and refer via className, Card styles should be in css and refer via className

Faculty collection
Design-05 update comments in methods: update, dumpOne (name, quantity, condition, owner)

**Comment by giorgio-tran** [comment]
### ListRoom.jsx

L10: Typo on <RoomItem>, should be <RoomItem />

L35-54: Might be able to export Carousel Items as their own components. The image src, and captions could be passed as props. 

L62-76: Accordion could be its own component. 

### FacultyRolesCollection.js

L40-45: Incorrect params, supposed to be role only.

L76-82: Might need to change this for Office role only, and combine with admin publication below.

L125-138: Wrong variables, supposed to be role only.

**Comment by JeromeWasserman** [comment]
ListRoom.jsx
-Design05 -More comments
FacultyRolesCollection.jsx
-L40-Incorrect params

**Comment by GrandeJames** [comment]
ListRoom:

L18, 20: DESIGN-05: Unnecessary comments

L42, L52: DESIGN-07: Explain image instead

FacultyRolesCollection:

L43, 44, 45: DESIGN-05: Params does not match comment

**Comment by malialiu** [comment]
ListRoom & FacultyRolesCollection: update comment

**Comment by graquepo** [comment]
ListRoom.jsx 
Add /change comments

FacultyRolesCollection.jsx
Change param comments
Change the components to just be for faculty, still has "stuffs" components
