### ISSUE TITLE
Review: Calendar.jsx and Home.jsx

### ISSUE THREAD

**Issue by giorgio-tran** [ics414t3/ics-osm#72]
## Review Branch

- [review-72](https://github.com/ics414t3/ics-osm/tree/review-72)

## Files to review

- [Calendar.jsx](https://github.com/ics414t3/ics-osm/blob/review-72/app/imports/ui/components/calendar/Calendar.jsx)
- [Home.jsx](https://github.com/ics414t3/ics-osm/blob/review-72/app/imports/ui/pages/Home.jsx)

## Checklists

- [Architecture](https://github.com/cammoore/campus-cravings/tree/master/checklists/architecture-checklist.md)
- [Design](https://github.com/cammoore/campus-cravings/tree/master/checklists/design-checklist.md)
- [JS](https://github.com/cammoore/campus-cravings/tree/master/checklists/js-checklist.md)
- [React](https://github.com/cammoore/campus-cravings/tree/master/checklists/react-checklist.md)

## Due Date

2/13/2023

**Comment by susankpma** [comment]
Home.jsx
Nothing much yet - as we continue to develop the system, more components will be added.


Calendar.jsx
Design-05: comment code

Javascript-07: remove console.logs Lines 12 - 17

**Comment by JeromeWasserman** [comment]
Home.jsx
-Design05,07
	-The code does not say what it wants to do and there is a lack of comments in the file
	-Rooms vacant, Rooms occupied, and Rooms out of commision can be put in components

Calendar.jsx
-Design05,07
	-Practically no comments in the file
-JS-07
	-console.logs exist in the file

**Comment by giorgio-tran** [comment]
### Calendar.jsx

L12-17: Remove console.logs

Add more comments

### Home.jsx

L6, 15: Home.jsx does not match ‘Landing’

**Comment by malialiu** [comment]
Home.jsx:
add some instruction for users?

Calendar.jsx:
add comments

**Comment by darquines** [comment]
Calender.jsx
- Design-05 Add comments for better clarity

**Comment by darquines** [comment]
Calender.jsx
- Design-05 Add comments for better clarity

**Comment by GrandeJames** [comment]
L12-17: DESIGN-05: Remove console logs

**Comment by graquepo** [comment]
Calendar.jsx 
Add comments

Home.jsx
Add comments
Add components
